export {default as Card} from './Card'
export {default as Faq} from './Faq'
export {default as Header} from './Header'
export {default as Key} from './Key'
export {default as Search} from './Search'
export {default as PageNumbers} from './PageNumbers'
export {default as Footer} from './Footer'